spring:
  rabbitmq:
    host: 192.168.124.14 # 主机名
    port: 5672 # 端口号 浏览器访问15672
    virtual-host: /hmall
    username: hmall
    password: 123456
    connection-timeout: 1s # 连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier，例如 初始等待时间 = 1000ms，倍数为1，下次等待时间 = 1000ms * 1 = 1000ms
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: correlated # 开启消息确认功能，并设置confirm类型
    publisher-returns: false # 开启消息发送失败返回功能

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS